### ISSUE TITLE
TEXT crashes

### ISSUE THREAD

**Issue by jedeoric** [assinie/Tele-Forth#1]
When you type "TEXT", it seems that it tries to switch into hires

**Comment by assinie** [comment]
The TEXT word in FORTH vocabulary came from the standard Forth's editor.
The TEXT and HIRES words used to switch the screen mode are in the GRAFX vocabulary, so you have to first type GRAFX in order to activate this vocabulary.

**Comment by jedeoric** [comment]
ok :)
